services:
  pg_db:
    image: postgres:16
    container_name: shop_core_db
    environment:
      POSTGRES_DB: shop_core_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  pg_db_test:
    image: postgres:16
    container_name: shop_core_db_test
    environment:
      POSTGRES_DB: shop_core_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
  postgres_data_test:
